### ISSUE TITLE
MapFiled CopyTo bug.

### ISSUE THREAD

**Issue by imurashka** [saltyJeff/UnityWifiDirect#1]
Hello! I found the bug in method MapFiled.CopyTo: int the line `if (arrayIndex + Count >= array.Length)` operator `>=` should be changed to `>`

**Comment by saltyJeff** [comment]
Can you give the filename and line number

**Comment by imurashka** [comment]
Sorry dude. My fail :) posted to wrong repo. You can delete this issue
