### ISSUE TITLE
Broadcastservice now throws NoSuchMethodError

### ISSUE THREAD

**Issue by Alexius1** [saltyJeff/UnityWifiDirect#2]
Line 48 of WifiDirectBase.cs
`hashMap.Call ("put", kvp.Key, kvp.Value);` 

does not work anymore since Unity needs the return type of the called method and HashMap.put(...) returns Value (the 2nd parameter).

This worked for me:
`string temp=hashMap.Call<string>("put", kvp.Key, kvp.Value);`

**Comment by saltyJeff** [comment]
latest commit fixed
