### ISSUE TITLE
Parsing connection string & sending messages

### ISSUE THREAD

**Issue by Alexius1** [saltyJeff/UnityWifiDirect#3]
These are the last two, I promise (ᗒᗣᗕ)՞.
First: deserializing in WifiDirectBase.cs doesn't work at all (infinite loop), here I fixed it (changed lines have comments):
```
public void onUglyTxtRecord (string uglyRecord) {
		int addrSplitAddress = uglyRecord.IndexOf ('&');
		string addr = uglyRecord.Substring (0, addrSplitAddress);
		string temp = uglyRecord.Substring (addrSplitAddress+1); //& isn't the first char
		int splitIndex = temp.IndexOf ('&');
		Dictionary<string, string> record = new Dictionary<string, string> ();
		while (splitIndex > 0) {
			int eqIndex = temp.IndexOf ('=');
			string key = temp.Substring (0, eqIndex); //change so that key is correct
			splitIndex = temp.IndexOf ('&');
			string value;
			if (splitIndex < 0) {
				value = temp.Substring (eqIndex + 1);

			} 
			else {
				value = temp.Substring (eqIndex + 1, splitIndex-eqIndex-1); //second argument is a length, not an index
				temp = temp.Substring (splitIndex + 1); //without it, infinite loop
			}
			record.Add (key, value);
		}
		Debug.Log("ugly record found");
		this.onTxtRecord (addr, record);
	}
```
Second: Messages are encoded in UTF-16 byte arrays, but decoded as UTF-8 (default for android devices)
Line 138 of UnityWifiDirect.java should be:
`String msg = new String(intent.getByteArrayExtra(WifiDirectHandler.MESSAGE_KEY),"UTF-16");`

I think the code should completely work with these 2 changes applied, please build the .aar file again.

PS.: Somehow you have to both host and search on both devices for a connection to be made, maybe a solution with only one broadcast/discover-service-method would be better. (No a device doesn't connect to itself in that case)

**Comment by saltyJeff** [comment]
I got it: check commit fe889fa4a2dacf51dc9ca79f929b3087255e3f09

This is just a thin wrapper around the WifiBuddy project so I'm not entirely sure why a peer needs to both broadcast and search, but I guess it makes sense because its P2P, so both Alice and Bob need to do a broadcast and search to send messages to each other
I noted this in the Readme.md

**Comment by Alexius1** [comment]
Thanks, it works now.
