### ISSUE TITLE
Unity Plugin WifiDirectBase.onUglyTextRecord 

### ISSUE THREAD

**Issue by JulianCortes** [saltyJeff/UnityWifiDirect#5]
`int splitIndex = temp.IndexOf('&');`

splitIndex will be -1 even if there is a record.

Example:
uglyText = 00:00:00:00&Key=value

With this type of text the dictionary will be empty.

**Comment by saltyJeff** [comment]
Just uploaded commit f26dfad . Changes the serialization format to use base64. 

In the old version, there's a if statement inside the while statement that checks if there is another '&', if there wasn't it would just slice to the end of the string so there shouldn't be an issue.
