### ISSUE TITLE
ACCESS_COARSE_LOCATION permission required

### ISSUE THREAD

**Issue by wtesler** [saltyJeff/UnityWifiDirect#6]
WiFi Direct requires coarse location permission. You may need to copy the AndroidManifest into Assets/Plugins/Android and manually add the permission before WiFi Direct will work in your game. Just a heads up to others.

**Comment by saltyJeff** [comment]
Are you sure? It works fine with only the network based perms for me. Also, permission incompatibility shouldn't be an issue if you're running marshmallow with user selected perms

**Comment by wtesler** [comment]
Yes, you can see it is required here: https://developer.android.com/training/connect-devices-wirelessly/wifi-direct.html#permissions

Also, I see it in the LogCat when debugging.

**Comment by saltyJeff** [comment]
can you pastebin your logcat for me? The base library doesn't [have that perm](https://github.com/Crash-Test-Buddies/WiFi-Buddy/blob/master/wifibuddy/src/main/AndroidManifest.xml)

**Comment by wtesler** [comment]
It showed the standard error for missing permissions in the logcat. Only after manually adding to the Manifest does a dialog appear requesting permission to use location when opening the game, even on Marshmallow.

Note that if your game uses location for other reasons, the permission will be automatically added.

You can look at the AndroidManifest generated by building your game in Build/StagingArea/AndroidManifest.xml and see if the permission is automatically being added.

**Comment by saltyJeff** [comment]
Sorry it took so long to reply (need to work on studies first). However, I recently updated the example to the latest version of the library and it worked for me. [https://github.com/saltyJeff/WifiDirectExample](https://github.com/saltyJeff/WifiDirectExample).

Here's a gist of the app's AndroidManifest: [https://gist.github.com/saltyJeff/0a46d589fd834a71897799ef8c644017](https://gist.github.com/saltyJeff/0a46d589fd834a71897799ef8c644017) (pulled with APK analyzer in Android Studio).

Something could be different with our build systems. I am running Unity 2017.1 on Win10 with the "Internal" build system for Android
